name: Maven Publish

# 触发条件：当代码推送到主分支时
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 拉取代码

    - name: Set up JDK 17
      uses: actions/setup-java@v2  # 设置JDK 版本为11
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install  # 执行Maven构建

    - name: Publish to GitHub Packages
      run: mvn deploy  # 部署构件到GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用GitHub提供的自动Token
